[project]
name = "rag-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chromadb>=1.0.13",
    "sentence-transformers>=4.1.0",
]

[tool.poetry.dependencies]
pandas = "*"
sentence-transformers = "*"
chromadb = "*"
